### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by umumum44**
Umthis code could easily be hacked does anyone know that

### CODE REVIEW

**Comment by gt-c** [comment]
plz no hacc

**Comment by gt-c** [comment]
and if ur being serious, mind explaining why?

**Comment by mastecodefixer** [comment]
Hi that was my old account

**Comment by mastecodefixer** [comment]
So anyone their

**Comment by gt-c** [comment]
Yes. What's wrong about the code?

**Comment by mastecodefixer** [comment]
gt_c want me to show u how this could be hacked

**Comment by mastecodefixer** [comment]
Who made this some guy named ethan ok I do not

**Comment by gt-c** [comment]
If you mean by actually hacking it then please don't

**Comment by mastecodefixer** [comment]
U should know I should not have to tell you the errors all you should know is it is unsecure

**Comment by mastecodefixer** [comment]
Bye

**Comment by gt-c** [comment]
all right bye troller

**Comment by mastecodefixer** [comment]
Frick off

**Pull request closed without merging**
